# action.yaml
name: 'WP Version SemVer Update'
description: 'Updates the Version of your Plugin or Theme'
author: 'Fred Bradley'
branding:
  icon: chevron-right,
  color: black
inputs:
  version:
    description: 'SemVer version'
    required: true
  file_path:
    description: 'the file we are updating'
    required: true
runs:
      using: 'node12'
      main: 'bumpversion.js'

